version: "3.8"
services:
  # https://hub.docker.com/r/itsthenetwork/nfs-server-alpine
  nfs:
    image: itsthenetwork/nfs-server-alpine:latest
    container_name: nfs
    restart: unless-stopped
    privileged: true
    environment:
      - SHARED_DIRECTORY=/data
    volumes:
      - /data/nfs-storage:/data
    ports:
      - 2049:2049
    networks:
      nfs_network:
        ipv4_address: 172.30.0.11

  nfs-client1:
    image: nfs-client:latest
    container_name: nfs-client1
    tty: true
    privileged: true
    networks:
      nfs_network:
        ipv4_address: 172.30.0.21
    cap_add:
      - SYS_ADMIN

  nfs-client2:
    image: nfs-client:latest
    container_name: nfs-client2
    tty: true
    privileged: true
    networks:
      nfs_network:
        ipv4_address: 172.30.0.22
    cap_add:
      - SYS_ADMIN

networks:
  nfs_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
